name: Meu Primeiro Workflow de CI

# Gatilho: rodar quando houver push ou pull request para a branch main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Trabalhos a serem executados
jobs:
  build:
    # Usar uma máquina virtual Ubuntu fornecida pelo GitHub
    runs-on: ubuntu-latest

    # Passos do nosso trabalho
    steps:
      # Passo 1: Usa uma Action pronta para baixar o código do repositório
      - name: 1. Fazendo o checkout do código
        uses: actions/checkout@v4

      # Passo 2: Executa um comando simples no terminal da máquina virtual
      - name: 2. Listando os arquivos do repositório
        run: ls -la
